// This file was autogenerated from the Testfile.strings file by ocstrings.
// Do not edit this file, edit the strings file and then re-generate this file based on it.

import Foundation

class TestfileStrings {
    public static var welcomeToStrings: String {
        return NSLocalizedString("welcomeToStrings", tableName: "Testfile", comment: "Welcome to Strings!")
    }

    public static func welcomeFormat(_ arg1: CVarArg) -> String {
        return String(format: NSLocalizedString("welcomeFormat", tableName: "Testfile", comment: "Welcome to Strings, %@!"), arguments: [arg1])
    }

    public static var welcomeLoggedOut: String {
        return NSLocalizedString("welcomeLoggedOut", tableName: "Testfile", comment: "I'm all alone.")
    }

    public static func faveNumber(_ arg1: UInt, _ arg2: Double) -> String {
        return String(format: NSLocalizedString("faveNumber", tableName: "Testfile", comment: "My favorite number is %1$08lx. That's like %2$08.5f"), arguments: [arg1, arg2])
    }

}
